name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Log in to Docker Hub (requires secrets for credentials)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Optional: Clean up local Docker images
      - name: Clean up Docker images
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/my-app:latest
