name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # Adjust branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using credentials stored as secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image using the Dockerfile in .github/scripts
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockertesting1:latest .github/scripts

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dockertesting1:latest

      # Optional Step 5: Clean up local Docker images
      - name: Clean up Docker images
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/dockertesting1:latest
